# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='Add your comment here.'),
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='Add your text here.'),
        ),
        migrations.AddField(
            model_name='reply',
            name='reply',
            field=models.TextField(default='Add your reply here.'),
        ),
    ]
