# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-17 01:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170917_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='favorited',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
