# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-17 03:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20170917_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(to='blog.Comment'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='favorited',
        ),
        migrations.AddField(
            model_name='post',
            name='favorited',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
