# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170530_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='C:\\Users\\Rob\\PycharmProjects\\afteralongday\\afteralongday\\assets\\img\\blog'),
        ),
    ]
