# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BathBombs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('img_name', models.CharField(default='img_coming_soon.jpg', max_length=120)),
            ],
            options={
                'verbose_name': 'Bath Bomb',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('contact_name', models.CharField(max_length=120)),
                ('contact_email', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='bathbombs',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afteralongday.Invoice'),
        ),
    ]
