# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-27 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BathBombs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.IntegerField(default=0)),
                ('in_stock', models.BooleanField(default=True)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='image/bathbombs')),
            ],
            options={
                'verbose_name': 'Bath Bomb',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('contact_name', models.CharField(max_length=120)),
                ('contact_email', models.CharField(max_length=120)),
                ('total_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('bath_bomb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afteralongday.BathBombs')),
            ],
        ),
    ]
