# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afteralongday', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='orders',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='afteralongday.Order'),
            preserve_default=False,
        ),
    ]
