# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afteralongday', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathbombs',
            name='description',
            field=models.TextField(default='Add description.'),
        ),
        migrations.AddField(
            model_name='bathbombs',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bathbombs',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
