# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-16 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afteralongday', '0002_invoice_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bathbombs',
            name='image',
        ),
        migrations.AddField(
            model_name='bathbombs',
            name='image_url',
            field=models.TextField(null=True),
        ),
    ]
