# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afteralongday', '0003_auto_20170530_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathbombs',
            name='image',
            field=models.ImageField(null=True, upload_to='C:\\Users\\Rob\\PycharmProjects\\afteralongday\\afteralongday\\assets\\img\\bathbombs'),
        ),
    ]
