# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afteralongday', '0004_bathbombs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bathbombs',
            name='price',
            field=models.CharField(default=0, max_length=120),
        ),
    ]
