# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-16 23:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('afteralongday', '0004_auto_20170916_0229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('feedback', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('display', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='bathbombs',
            name='image_url',
            field=models.TextField(default='/static/image/bathbombs/makeitmine.jpg'),
        ),
    ]
