# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afteralongday', '0006_auto_20170601_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bathbombs',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoice',
            name='bath_bombs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='afteralongday.BathBombs'),
        ),
    ]
