# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afteralongday', '0009_auto_20170601_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='bathbomb',
            new_name='bath_bomb',
        ),
        migrations.AlterField(
            model_name='bathbombs',
            name='image',
            field=models.ImageField(null=True, upload_to='image/bathbombs'),
        ),
    ]
