# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afteralongday', '0011_auto_20170822_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='total_price',
        ),
    ]
