# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afteralongday', '0012_remove_invoice_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
