# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-25 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afteralongday', '0013_invoice_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='invoice',
        ),
    ]
