# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-27 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('feedback', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('display', models.BooleanField(default=False)),
            ],
        ),
    ]
