# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_testimonial_display'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='description',
            new_name='feedback',
        ),
    ]
